### ISSUE TITLE
Update signer docs to be more explicit about relevancy date

### ISSUE THREAD

**Issue by cuevasm** [stacks-network/sbtc-docs#114]
https://stacks-network.github.io/sbtc-docs/nakamoto-signer-developer-guide.html

Something like a callout/highlighted section at the top that says: "Signing functionality will only become active and relevant on the Stacks mainnet at the release of the Nakamoto upgrade, currently expected in early 2024. Prospective signers and Stacking providers can contact signers@sbtc.tech for support and additional information."

**Comment by kenrogers** [comment]
Added in the disclaimer section: https://stacks-network.github.io/sbtc-docs/nakamoto-signer-developer-guide.html

Callout looked funky when I deployed so I just made it bold, callouts in MdBook are annoying, will make this an actual callout in GitBook.
