### ISSUE TITLE
Rebrand sBTC releases

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc-docs#16]
## Context
In the sprint planning meeting today, it was raised that the current release names are confusing. The current releases are named Alpha, Mini, MVP and 1.0 and are outlined in this doc chapter: https://github.com/stacks-network/sbtc-docs/blob/master/src/sbtc-releases.md

We should create alignment around a better set of names, and rebrand the releases.

## Definition of done
- The releases are renamed in the docs and everyone is happy.

**Comment by muneeb-ali** [comment]
My two cents here are to stay away from terms like Custodial and Stacking Pool. For Custodial, people have short attention spans and if they once read somewhere that "sBTC is custodial" it'll take ages to clarify that "no, no actually it was just one version of sBTC which was". For "Stacking Pool", I think the term stacking is used mostly inside the current Stacks ecosystem and might be confusing to outsiders. They'd also not know why I'm participating in a stacking pool for being a signer (people usually participate in pools for other reasons). My suggestion would be:

- sBTC mini 
- sBTC 1.0
- sBTC 1.1

I'm dropping references to sBTC Alpha intentionally; it's an internal thing and no longer the focus so just removing it can be the simple path. I'm not tied to the name "mini". There is some chats with comms working group on this and maybe some better suggestion comes out of there. If that happens then can replace "mini" with that <new name> but 1.0 and 1.1 feel pretty good to me. Looking forward to seeing what others think -- thanks!

**Comment by andrerserrano** [comment]
> sBTC mini
> sBTC 1.0
> sBTC 1.1

I like that framing. We could also break out the release name and version number, like this: 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e07eb4a4-7fff-e5a9-fa5e-1e6cea861f8f"><div dir="ltr" style="margin-left:-7.5pt;" align="left">

Release Name | sBTC Mini | sBTC Mini v2 | sBTC Nakamoto | sBTC Nakamoto v2
-- | -- | -- | -- | --
Version | 0.1 | 0.2 | 1.0 | 1.1

</div></b>

“MVP” is a useful way for us to think internally about shipping a product with a simple scope, not an actual release candidate. 

As for whether to keep the “Mini” branding, an alternative could be “Beta” since it is generally more feature complete and more focused on usability testing with users. I will work with the comms group to define which would be preferred for public audiences and will update here with any significant findings.

**Comment by netrome** [comment]
> Release Name 	sBTC Mini 	sBTC Mini v2 	sBTC Nakamoto 	sBTC Nakamoto v2
> Version 	0.1 	0.2 	1.0 	1.1

Nice, I like this!

**Comment by stjepangolemac** [comment]
> We could also break out the release name and version number, like this...

Looks really good! The progression is clear and naming doesn't involve any "sticky" terms. 👍

**Comment by netrome** [comment]
> I'm dropping references to sBTC Alpha intentionally

If there is any interest in building on alpha, I'd still like to have the release documented - but for the time being we can keep the name alpha then and give it version 0.0.1

**Comment by muneeb-ali** [comment]
I like 0.1, 0.2, 1.0, and 1.1 as they can be consistent with engineers. The comms working group can then assign a name like "mini" or something else to 0.2 which is fine (they don't really have a name yet).

It separates clarity for comms for engineers vs comms WG and can work -- thanks!

**Comment by andrerserrano** [comment]
Request for feedback: What about rebranding "sBTC Mini" to "sBTC Developer Release"? 

This could help to reduce confusion about the purpose of this version by calling it exactly **what it is** and **who it is targeted for**. (Thanks to Elena from the comms WG for this suggestion)

**Comment by netrome** [comment]
> Request for feedback: What about rebranding "sBTC Mini" to "sBTC Developer Release"?
> 
> This could help to reduce confusion about the purpose of this version by calling it exactly **what it is** and **who it is targeted for**. (Thanks to Elena from the comms WG for this suggestion)

I like it!

**Comment by netrome** [comment]
I have merged the updated release names now as:

| Version | Name (optional)  | Released |
|---------|------------------|----------|
| 0.0.1   |                  | ✅       |
| 0.1     | sBTC Developer   |          |
| 0.2     | sBTC Developer v2|          |
| 1.0     | sBTC Nakamoto    |          |
| 1.1     | sBTC Nakamoto v2 |          |

Please let me know any thoughts or concerns and I can address them as a follow-up.
