### ISSUE TITLE
Document precise withdrawal signature format

### ISSUE THREAD

**Issue by netrome** [stacks-network/sbtc-docs#18]
### Definition of done
The ECDSA signature of the withdrawal requests is documented in a non-ambiguous way.

**Comment by netrome** [comment]
@MarvinJanssen is blocked on this currently. I'll prioritize getting this written down.

**Comment by MarvinJanssen** [comment]
Thanks!

**Comment by netrome** [comment]
PR ready https://github.com/stacks-network/sbtc-docs/pull/60 @MarvinJanssen let me know if anything is unclear or if you need more detail.
