### ISSUE TITLE
Bootstrapping sBTC DR

### ISSUE THREAD

**Issue by MarvinJanssen** [stacks-network/sbtc-docs#34]
Document how to bootstrap sBTC DR. It should include:

1. Deploying the contracts.
2. Sending the `upgrade` transaction to enable the protocol contracts.
3. Getting the pool to an active state so that signers can join and vote.

**Comment by MarvinJanssen** [comment]
@jferrant in this issue we will discuss how to bootstrap sBTC Developer Release.

**Comment by friedger** [comment]
outdated
