### ISSUE TITLE
devnet: clarinet: need to specify version to install

### ISSUE THREAD

**Issue by EmbeddedAndroid** [stacks-network/sbtc-docs#95]
I was running through the new DR v0.2 devnet docs (thanks @friedger!!) and noticed an issue running the `deploy_contracts.sh`.

We link to: https://github.com/hirosystems/clarinet for installation steps, however if you happen to try to install the prebuilt binaries:

You are directed to: https://github.com/hirosystems/clarinet/blob/develop/README.md?plain=1#L49

Which downloads v0.27.0 of clarinet, which does not have the deployment subcommands, and thus `deploy_contracts.sh` fails to execute.

I just want to flag this for discussion, as this is a stumbling point for a new user. We probably want to at a minimum, prescribe the minimum clarinet version that we have tested with.

**Comment by friedger** [comment]
Has been fixed in #109
