### ISSUE TITLE
Clarify differences between versions 

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-docs#99]
sBTC DR 0.1 has other properties than described in SIP 25 and as described in this docs.

Where is the place to summarise the differences?

sBTC DR 0.1 support OP_RETURN, is custodial, does not support withdrawal via stx txs.

sBTC DR 0.2 support OP_RETURN and commit reveal

SIP 25 sBTC is trustless, support only OP_RETURN, and only supports withdrawal via stx txs.

**Comment by stjepangolemac** [comment]
I thought OP_RETURN is not the end goal and commit-reveal is?

**Comment by setzeus** [comment]
Surfacing this issue as linked to ClarityWG sprint sync.
